FROM ubuntu:latest

# Install dependencies
RUN apt-get update && apt-get install -y zip nano wget curl git
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

# Set the working directory
WORKDIR /workspace

# Copy application files
COPY server.mjs .

# Expose the port that the server will use
EXPOSE 3000

# Start the server
CMD ["node", "server.mjs"]



