FROM ubuntu:latest

RUN apt-get update && apt-get install -y zip nano wget curl git nodejs
RUN curl -sL https://npmjs.org/install.sh | bash -

WORKDIR /workspace

COPY server.mjs .

EXPOSE 80

CMD ["node","server.mjs"]