version = 0.1
[default.deploy.parameters]
stack_name = "sam-eventbridge-order"
resolve_s3 = true
s3_prefix = "sam-eventbridge-order"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
