AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  PutOrderFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: handler.putOrder
      Runtime: nodejs18.x
      CodeUri: .
      Policies:
        - Statement:
            - Sid: EventBridgePutEvents
              Effect: "Allow"
              Action:
                - "events:PutEvents"
              Resource: "*"
      Events:
        PutOrderAPI:
          Type: Api
          Properties:
            Path: /order
            Method: POST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TestingAPI:
    Description: "API Gateway endpoint URL for Prod stage for Order function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/order"
